### ISSUE TITLE
Error in executing predict_pitch.py

### ISSUE THREAD

**Issue by saxenarohit** [biboamy/instrument-prediction#2]
Unknown: exceptions.AttributeError: 'Spectrograms' object has no attribute 'train_id

Can you also tell me which version of tensorflow you are using.

I am using
python 2.7 (as cPickle is used)
tensorflow 1.5

**Comment by biboamy** [comment]
Hello, sorry for the late response. I have updated the code and it's now working fine. I tested it on python3 and tensorflow==2.0.0. Please let me know if you have other questions.
