### ISSUE TITLE
Possibly missing data processing pipeline for training data preparation?

### ISSUE THREAD

**Issue by kukas** [biboamy/instrument-prediction#3]
Hi, 

I wanted to reproduce your results from the ISMIR paper and train my own models based on your code. I skimmed the code in `process.py` and tried to search for where do you generate the `ex_data/cqt/xtr.npy` and `ytr.npy` files but I couldn't find the relevant code snippets. I think that there are some scripts missing in this repository. 

Can you please upload the remaining code so that we can reproduce your experiments in the paper? Thank you!

**Comment by biboamy** [comment]
Hello, sorry for the late response. I just update the code. Please find it in the process.py script, and also please let me know if you have further questions!
